var a = 25;
var b = 2;
var c = a + b;
var d = a - b;
var e = a * b;
var f = a / b;
var g = a % b;
var h = a ** b;
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(g);
console.log(h);
