var a = 100;
var b = -123;
var c = 1423.342;
var d = 132 - 43;
var e = 0.2;
var f = "2347";
var g = "Adarsh";
console.log(Number.isSafeInteger(a));
console.log(Number.isSafeInteger(b));
console.log(Number.isSafeInteger(c));
console.log(Number.isSafeInteger(d));
console.log(Number.isSafeInteger(e));
console.log(Number.isSafeInteger(f));
console.log(Number.isSafeInteger(g));
